CXX = g++
CXXFLAGS = -Wall -g

default: main

main:
	$(CXX) $(CXXFLAGS) -c DynIntStack.cpp -o DynIntStack.o
	$(CXX) $(CXXFLAGS) -c burakkuz_Kuz_Burak_hw4.cpp -o burakkuz_Kuz_Burak_hw4.o
	$(CXX) $(CXXFLAGS) burakkuz_Kuz_Burak_hw4.o DynIntStack.o -o main

